name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
        
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
  
      - name: Build
        run: |
          npm install
          npm run build

      - name: Populate Version and Download Links in system.json
        id: populate_system_json
        uses: microsoft/variable-substitution@v1
        with:
          files: "system.json"
        env:
          version: ${{github.event.release.tag_name}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

      - name: Populate System Version for Compendium Items
        id: populate_compendium_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "src/packs/*/*.yml"
        env:
          systemVersion: ${{github.event.release.tag_name}}

      - run: zip -r system.zip . -x node_modules/\* src/\*

      - name: Update Release with Files
        id: update_release_files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          artifacts: "./system.json, ./system.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
